behaviors:
  SoccerAI:
    trainer_type: poca
    hyperparameters:
      batch_size: 4096          
      buffer_size: 40960        
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: linear

    network_settings:
      normalize: true
      hidden_units: 512        
      num_layers: 4            
      memory:
        sequence_length: 64    
        memory_size: 256       

    reward_signals:
      extrinsic:
        gamma: 0.995           
        strength: 1.0

    keep_checkpoints: 5
    checkpoint_interval: 500000 
    summary_freq: 20000         
    max_steps: 50000000          
    time_horizon: 256          

environment_parameters:
  max_env_steps: 3000.0        
  lesson_index: 0.0            