behaviors:
  SoccerAI:
    trainer_type: poca
    hyperparameters:
      batch_size: 2048          # Increased for 1v1 to stabilize learning with more complex interactions
      buffer_size: 20480        # Standard 10x batch_size
      learning_rate: 0.0003
      beta: 0.005               # Moderate entropy to allow for creative dribbling
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear

    network_settings:
      normalize: true           # Vital for Vector Observations (Normalization of coordinates/velocities)
      hidden_units: 256
      num_layers: 2
      memory:
        sequence_length: 64     # Increased to help agents remember opponent positioning
        memory_size: 128

    reward_signals:
      extrinsic:
        gamma: 0.995            # High gamma to help agents value long-term defensive setups
        strength: 1.0

    # ==========================================================================================
    # SELF-PLAY CONFIGURATION (Required for 1v1)
    # This prevents the POCATrainer from treating opponents as teammates.
    # ==========================================================================================
    self_play:
      window: 10                # Keep the 10 most recent versions of the brain to play against
      play_against_latest_model_ratio: 0.5
      save_steps: 50000         # Save a "snapshot" for the pool every 50k steps
      swap_steps: 20000         # Change the opponent version frequently
      team_change: 100000       # Interval to refresh the entire matchup logic

    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 20000000         # 1v1 takes longer to reach equilibrium
    time_horizon: 256           # Long enough to connect a defensive steal to a counter-attack goal
    summary_freq: 50000

    # Point this to your result from the 1v0 training
    init_path: results/0/SoccerAI/SoccerAI-10000001.pt

environment_parameters:
  max_env_steps: 3500.0         # Give them enough time for back-and-forth play
  lesson_index: 1.0             # Set to 1.0 for your 1v1 Scenario