behaviors:
  SoccerAI:
    trainer_type: poca
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear

    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2         # Change back to 2 to match 1v1
      memory:
        sequence_length: 64
        memory_size: 128    # Change back to 128 to match 1v1

    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0

    # ==============================================================================
    # SELF-PLAY: Competitive Balance
    # In 2v1, the defender (1) needs to play against the pair (2).
    # ==============================================================================
    self_play:
      window: 10
      play_against_latest_model_ratio: 0.5
      save_steps: 50000
      swap_steps: 20000
      team_change: 100000

    keep_checkpoints: 5
    max_steps: 20000000
    time_horizon: 1000        # Much higher to connect "Teammate Movement" to "Final Goal"
    summary_freq: 20000

    # Initialize from your 20M step 1v1 result
    init_path: results/1/SoccerAI/SoccerAI-20000185.pt

environment_parameters:
  max_env_steps: 4000.0       # Slightly longer matches for 2v1 positioning
  lesson_index: 2.0           # Assuming index 2 is your new 2v1 Scenario